function [fitresult, gof, smROI] = GaussFit(x, y, ROI)
%CREATEFIT1(X,Y,ROI)
%  Create a fit.
%
%  Data for 'ROI2' fit:
%      X Input : x
%      Y Input : y
%      Z Output: ROI
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Jun-2015 20:25:42


%% Fit the surface
[xData, yData, zData] = prepareSurfaceData( x, y, ROI );

[fltfit, ~] = fit([xData, yData], zData, 'loess');
% Evaluate the smoothed ROI at each x and y
smROI = feval(fltfit,x,y);

[xData, yData, zData] = prepareSurfaceData( x, y, smROI );
% Set up fittype and options.
a0 = max(max(smROI));
ft = fittype( 'a*exp(-((x-x0)^2)/(2*b^2)-((y-y0)^2)/(2*c^2))+d', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [0 0 0 -Inf -Inf -Inf];
opts.StartPoint = [a0 5 5 1 1 1];
opts.Upper = [Inf Inf Inf Inf 30 30];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'ROI2' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'ROI2', 'ROI vs. x, y', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'x' );
% ylabel( 'y' );
% zlabel( 'ROI' );
% grid on


